rule sort_local:
    input:
        "data/numbers.txt",
    params:
        output_dir="results"
    output:
        "results/sorted_numbers.txt"
    shell:
        """
        mkdir -p {params.output_dir} && \
        sort {input} > {output}
        """

rule sort_script:
    input:
        "data/numbers.txt",
    params:
        output_dir="results"
    output:
        "results/sorted_numbers_script.txt"
    script:
        "scripts/sort.sh"

rule sort_docker:
    input:
        "data/numbers.txt",
    params:
        output_dir="results"
    output:
        "results/sorted_numbers_container.txt"
    container:
        "docker://python:3.12"
    script:
        "scripts/sort.sh"

rule hello_lxbatch:
    output:
        "local_hello.txt"
    shell:
        """
        echo "hello hello $(date)" > {output}
        """

rule sort_chtc:
    input:
        "data/numbers.txt",
    output:
        "results/sorted_numbers.txt"
    resources:
        htcondor_transfer_input_files="placeholder.txt",
        htcondor_transfer_output_files="logs/out.log"
    script:
        "scripts/sort.sh"
