[project]
name = "snakemake-lxplus-example"
version = "0.1.0"
description = "Snakemake hello world example on LXPLUS and lxbatch"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
example = """
rm -rf results \
&& snakemake --verbose --cores 1 --printshellcmds --snakefile workflow/Snakefile sort_script
"""

lxbatch-example = """
snakemake --verbose --cores 1 --printshellcmds --executor htcondor --jobs 1 --snakefile workflow/Snakefile hello_lxbatch
"""

apptainer-example = """
snakemake --cores 1 --printshellcmds --software-deployment-method apptainer --snakefile workflow/Snakefile sort_docker
"""

[dependencies]
python = "3.11.*"
snakemake = "==8.10.4"
htcondor = "==23.5.3"
python-htcondor = "==23.5.3"

[pypi-dependencies]
snakemake-executor-plugin-htcondor = { version = "==0.1.2" }

[feature.cookie.tasks]
lxbatch-init = """
mkdir -p $HOME/.config/snakemake \
&& cookiecutter --no-input gh:Snakemake-Profiles/htcondor profile_name=lxbatch htcondor_log_dir="${HOME}/.condor_jobs" \
&& rm -rf $HOME/.config/snakemake/lxbatch \
&& mv lxbatch $HOME/.config/snakemake/
"""

[feature.cookie.dependencies]
cookiecutter = "*"

[environments]
cookie = ["cookie"]
