[project]
name = "snakemake-lxplus-example"
version = "0.1.0"
description = "Snakemake hello world example on LXPLUS and lxbatch"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
example = """
rm -rf results \
&& snakemake --verbose --cores 1 --printshellcmds --snakefile workflow/Snakefile sort_script
"""

lxbatch-example = """
snakemake --profile .profiles/lxbatch --snakefile workflow/Snakefile --verbose --cores 1 --printshellcmds hello_lxbatch
"""

apptainer-example = """
snakemake --cores 1 --printshellcmds --software-deployment-method apptainer --snakefile workflow/Snakefile sort_docker
"""

[dependencies]
python = "3.11.*"
snakemake = "==8.10.6"
python-htcondor = "==23.5.3"
snakemake-executor-plugin-cluster-generic = "==1.0.9"

[feature.cookie.tasks]
lxbatch-init = """
mkdir -p .profiles \
&& rm -rf .profiles/lxbatch \
&& cookiecutter \
--no-input \
--output-dir .profiles/ \
gh:Snakemake-Profiles/htcondor \
profile_name=lxbatch \
htcondor_log_dir=$PWD/.condor_jobs \
location_cern=true\
&& cp patches/config.v8+.yaml .profiles/lxbatch/
"""

[feature.cookie.dependencies]
cookiecutter = "*"
sed = ">=4.8"

[environments]
cookie = ["cookie"]
