[workspace]
name = "snakemake-lxplus-example"
version = "0.1.0"
description = "Snakemake hello world example on LXPLUS and lxbatch"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
example = """
rm -rf results \
&& snakemake --verbose --cores 1 --printshellcmds --snakefile workflow/Snakefile sort_script
"""

lxbatch-example = """
snakemake --profile .profiles/lxbatch --snakefile workflow/Snakefile --verbose --cores 1 --printshellcmds hello_lxbatch
"""

apptainer-example = """
snakemake --cores 1 --printshellcmds --software-deployment-method apptainer --snakefile workflow/Snakefile sort_docker
"""

[tasks.chtc-example]
cmd = """
snakemake --printshellcmds --executor htcondor --shared-fs-usage none --snakefile workflow/Snakefile sort_chtc
"""

[dependencies]
snakemake = ">=9.16.3,<10"
python-htcondor = ">=24.5.1,<25"

# [feature.cookie.tasks]
# lxbatch-init = """
# mkdir -p .profiles \
# && rm -rf .profiles/lxbatch \
# && cookiecutter \
# --no-input \
# --output-dir .profiles/ \
# gh:Snakemake-Profiles/htcondor \
# profile_name=lxbatch \
# htcondor_log_dir=$PWD/.condor_jobs \
# location_cern=true \
# && cp patches/config.v8+.yaml .profiles/lxbatch/
# """

[pypi-dependencies]
snakemake-executor-plugin-htcondor = { git = "https://github.com/htcondor/snakemake-executor-plugin-htcondor-archive.git", branch = "main" }
